class Processor
  def initialize(order, client_from = nil, client_to = nil)
    @order = order
    @client_from = client_from || order.server_from.client
    @client_to = client_to || order.server_to.client
  end

  def process!
    begin
      case @order.url_type
      when :post
	copy_post(@order.url_id)
      when :wiki_page
	copy_wiki_page(@order.url_id)
      when :pool
	copy_pool(@order.url_id)
      else
	[:failure, "unknown url type", nil]
      end
    rescue Faraday::TimeoutError => e
      [:timeout, e.to_s, nil]
    rescue Exception => e
      [:failure, e.to_s, nil]
    end
  end

  def copy_post(id)
    resp = @client_from.get_post(id)
    return failure "could not find post '#{id}' in source", resp unless resp.success?

    post = resp
    source = post.source
    tags = post.tags
    rating = post.rating

    tags.each do |tag|
      # tag
      unless @client_to.find_tag_by_name(tag).success?
	resp = @client_from.find_tag_by_name(tag)
	return failure "could not find tag '#{tag}' in source", resp unless resp.success?

	resp = @client_to.create_tag(tag)
	return failure "could not create tag '#{tag}' in sink", resp unless resp.success?
      end

      # wiki page
      unless @client_to.find_wiki_page_by_name(tag).success?
	resp = @client_from.find_wiki_page_by_name(tag)
	if resp.success?
	  resp = @client_to.create_wiki_page(resp.result)
	else
	  wiki_page = WikiPage.new(
	    title: tag,
	    body: "(Autogenerated by Kiki)",
	    other_names: [])
	  resp = @client_to.create_wiki_page(wiki_page)
	end
	return failure "could not create wiki page '#{tag}' in sink", resp unless resp.success?
      end
    end

    resp = @client_to.upload_post(post)
    return failure "could not upload post '#{source}' to sink", resp unless resp.success?

    [:success, nil, resp]
  end

  def copy_wiki_page(id)
    resp = @client_from.get_wiki_page(id)
    return failure "could not find wiki page '#{id}' in source", resp unless resp.success?

    if @client_to.find_wiki_page_by_name(resp.title).success?
      return failure "wiki page with name '#{resp.title}' already exists", resp
    end

    wiki_page = resp
    resp = @client_to.create_wiki_page(wiki_page)
    return failure "could not create wiki page '#{wiki_page.title}' in sink", resp unless resp.success?

    [:success, nil, resp]
  end

  def copy_pool(id)
    resp = @client_from.get_pool(id)
    return failure "could not find pool '#{id}' in source", resp unless resp.success?

    [:failure, nil, nil]
  end

  private

  def failure(message, resp)
    [:failure, message, resp]
  end
end
